schema_version: 1

context:
  name: microdot
  version: "2.6.2"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/microdot-${{ version }}.tar.gz
  sha256: 7bb9a69fa97a47d8fe07e61d9dd405804744132ca52d26705cf1173431ff7f4b

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=61.2
    - pip
  run:
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - microdot
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  summary: The impossibly small web framework for MicroPython
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/miguelgrinberg/microdot
  documentation: https://microdot.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - thewchan
